[phases.setup]
nixPkgs = ["...", "openssl"]

[phases.build]
cmds = [
  "yarn install --frozen-lockfile",
  "yarn prisma generate", 
  "yarn build"
]

[start]
cmd = "yarn start"

[variables]
NODE_ENV = "production"