# .do/app.yaml
# Digital Ocean App Platform Specification

name: ad-hub
region: west

services:
  - name: web
    # GitHub connection
    github:
      repo: richtunnel/AthleticsDashboard
      branch: main
      deploy_on_push: true

    # Build configuration
    build_command: yarn run build

    # Run configuration
    run_command: yarn start

    # Environment
    environment_slug: node-js

    # Instance size
    instance_count: 1
    instance_size_slug: basic-xs # $5/month (512MB RAM, 1 vCPU)
    # Options: basic-xs, basic-s, basic-m, professional-xs, professional-s

    # HTTP configuration
    http_port: 3000

    # Health check
    health_check:
      http_path: /api/health
      initial_delay_seconds: 60
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3

    # Environment variables
    envs:
      - key: NODE_ENV
        value: production

      - key: NEXTAUTH_URL
        value: ${APP_URL}

      - key: NEXTAUTH_SECRET
        scope: RUN_TIME
        type: SECRET

      - key: DATABASE_URL
        scope: RUN_AND_BUILD_TIME
        type: SECRET

      - key: GOOGLE_CLIENT_ID
        scope: RUN_AND_BUILD_TIME
        type: SECRET

      - key: GOOGLE_CLIENT_SECRET
        scope: RUN_AND_BUILD_TIME
        type: SECRET

      - key: GOOGLE_REDIRECT_URI
        value: ${APP_URL}/api/auth/callback/google

      - key: RESEND_API_KEY
        scope: RUN_TIME
        type: SECRET

      - key: OPENAI_API_KEY
        scope: RUN_TIME
        type: SECRET

      - key: GOOGLE_MAPS_API_KEY
        scope: RUN_TIME
        type: SECRET

    # Routes
    routes:
      - path: /

databases:
  - name: postgres-db
    engine: PG
    version: "15"
    size: db-s-1vcpu-1gb # $15/month
    num_nodes: 1
    production: true
# Optional: Static site for docs or landing page
# static_sites:
#   - name: landing-page
#     github:
#       repo: YOUR_GITHUB_USERNAME/landing-page-repo
#       branch: main
#     build_command: npm run build
#     output_dir: out
#     routes:
#       - path: /

# Workers (for background jobs - optional)
# workers:
#   - name: email-worker
#     github:
#       repo: YOUR_GITHUB_USERNAME/YOUR_REPO_NAME
#       branch: main
#     build_command: npm run build
#     run_command: npm run worker:email
#     instance_count: 1
#     instance_size_slug: basic-xs
