name: athletics-dashboard
region: sfo3
services:
  - name: web
    image:
      registry_type: docregistry
      repository: athletics-dashboard
      tag: TAG_TO_REPLACE # Replaced by pipeline
    http_port: 3000
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /
    envs:
      - key: NODE_ENV
        value: production
        scope: RUN_TIME
      # Add secrets via DO dashboard
      # Example:
      # - key: NEXTAUTH_URL
      #   value: https://your-domain.example.com
      #   scope: RUN_TIME
      # - key: DATABASE_URL
      #   scope: RUN_TIME
      #   type: SECRET
