import type { Metadata } from "next";

import HomePageContent from "@/components/home/HomePageContent";
import faqsData from "@/data/faq";

export const metadata: Metadata = {
  title: "Opletics | Athletic Management Software for Coaches & Directors",
  description:
    "Opletics is the premier sports software for athletic departments. Our athletic management software gives athletic directors AI-powered tools to automate scheduling, sync calendars, send email campaigns, and manage teams — the best alternative to Direct Athletics and Teamworks.",
  keywords: [
    // ── Core product ──────────────────────────────────────────────────────
    "opletics",
    "sports source",
    "sports-source",
    "sport-source",
    "sport source",
    "sports spreadsheet",
    "AMS",
    "new ams",
    "best ams",
    "athletic management system",
    "athletic management tool",
    "athletic management ai",
    "sports management",
    "league management",
    "league management system",
    "sports software",
    // ── Features ──────────────────────────────────────────────────────────
    "campaign manager",
    "email campaigns",
    "score tracker",
    "game schedule",
    "ad chat",
    "AD Channel",
    "athletics chat",
    "athlete management",
    "easy game finder",
    "schedule games",
    "calendar sync",
    "automate workflow",
    "automate schedules",
    "automate games schedule",
    "automate sports schedule",
    "automate spreadsheet",
    "game day",
    "centralized ams",
    "athletes desk",
    "adhub",
    "athletics hub",
    "athletic directors hub",
    "athletic directors connect",
    "athletic directors exchange",
    "athletic director calendars",
    "athlete monitoring",
    "smart athlete",
    // ── Audience ──────────────────────────────────────────────────────────
    "athletic directors",
    "becoming an athletic director",
    "learn how to become an AD",
    "how to become the best athletic director",
    "Athletic Director directory",
    "athletic directors conference overview",
    "software for athletic directors",
    "software for coaches",
    "software tools for coaches",
    "tools for athletic directors",
    "tools for coaches",
    "tools for staff",
    "best athletic director tools",
    "college tools",
    "athletic director communication",
    "best way for athletic director to communicate",
    // ── Competitor alternatives ───────────────────────────────────────────
    "Direct Athletics",
    "teamworks",
    "Teambuilder",
    "team builder",
    "Kinduct",
    "athlete SR",
    "hubletics",
    "sportsyou",
    "sports you",
    "Zapier",
    "product hunt",
    // ── Discovery ────────────────────────────────────────────────────────
    "hidden gems",
    "sports secrets",
    "secret platforms",
    "secret dashboards",
    "fundraising",
    "sports agents",
    // ── Spreadsheet / Excel / Google Sheets ──────────────────────────────
    "school software",
    "spreadsheet automation software",
    "spreadsheet ai tools",
    "spreadsheet ai assistant",
    "ai spreadsheet software",
    "ai-powered spreadsheet tools",
    "smart spreadsheet tools",
    "smart spreadsheets for athletic directors",
    "smart spreadsheets for coaches",
    "spreadsheet management software",
    "spreadsheet workflow automation",
    "spreadsheet dashboard for coaches",
    "school spreadsheet software",
    "automate google sheets tasks",
    "automate excel workflows",
    "google sheets automation for schools",
    "excel automation for athletic departments",
    "google sheets formulas for sports schedules",
    "how to filter games in google sheets",
    "how to add filters in excel",
    "how to organize athletic schedules",
    "how to track schedules in excel",
    "how to organize sports data in google sheets",
    "how to build a searchable database in google sheets",
    "how to create a sports schedule spreadsheet",
    "creating a sports schedule",
    "team scheduling spreadsheet",
    "ai that automates spreadsheets",
    "syncing my calendar to my excel",
    "syncing my calendar to my spreadsheet",
    "how to sync my spreadsheet to my calendar",
    "how to sync my spreadsheet to my google calendar",
    "how to automate my spreadsheet",
    "how to automate my sports schedule",
    // ── Email / Communication Automation ─────────────────────────────────
    "bulk email software for schools",
    "mass email tools for schools",
    "email automation with excel",
    "email automation with google sheets",
    "how to send emails with google sheets",
    "how to send emails with excel",
    "how to send emails from my spreadsheet",
    "how to send emails from my excel spreadsheet",
    "sending emails with google sheets",
    "how can i send multiple emails to parents",
    "google sheets mail merge",
    "email merge for athletic departments",
    "parent communication software",
    "automated email reminders for games",
    "send schedule updates automatically",
    "school messaging software",
    "what's the best way for athletic directors to send emails",
    // ── AI / Automation ───────────────────────────────────────────────────
    "ai for athletic departments",
    "ai sports scheduling software",
    "ai assistant for schools",
    "ai scheduling assistant",
    "ai tools for school administrators",
    "ai tools for ADs",
    "ai tools for coaches",
    "AI for schools",
    "best ai tech for athletic directors",
    "athletic department ai tools",
    "ai productivity tools for coaches",
    "ai for sports management",
    "ai-powered school software",
    "ai software for scheduling games",
    "automate school operations with ai",
    "smart scheduling assistant",
    // ── How-To / Search Intent ─────────────────────────────────────────────
    "how to create a game schedule",
    "how to create a teams list",
    "how do athletic directors schedule games",
    "how do athletic directors manage schedules",
    "how to manage a sports schedule",
    "how to organize game schedules",
    "easiest way to schedule games",
    "how to reduce scheduling conflicts",
    "how to manage multiple team schedules",
    "how to save time with spreadsheets",
    "how coaches manage schedules",
    "how to manage sports communications",
    "how to filter sports schedules",
    "how to create automated reports in google sheets",
    "how to manage school sports data",
    "tools to automate athletic administration",
    "how to schedule games for multiple teams",
    "how to organize a sports season",
    "help sorting game schedule",
    "help creating spreadsheet search",
    "how can i find software that automates my sports schedule",
    "tricks to sport scheduling",
    // ── Organization / Calendar ───────────────────────────────────────────
    "keeping my sports schedule organized",
    "organizing my sports schedule",
    "organizing my athletics schedule",
    "organizing my athletics sports schedule",
    "how can I create iPhone notifications for my game schedules",
  ],
  alternates: {
    canonical: "/",
  },
  openGraph: {
    title: "Opletics | Athletic Management Software for Coaches & Directors",
    description:
      "Opletics is the premier sports software for athletic departments. Automate scheduling, sync to Google Calendar, send email campaigns, and manage teams with AI-powered tools. The best alternative to Direct Athletics and Teamworks.",
    url: "/",
    images: [
      {
        url: "/assets/images/opletic-dash-sample.png",
        width: 1200,
        height: 630,
        alt: "Opletics AMS dashboard — best athletic management software for athletic directors and coaches",
      },
    ],
  },
};

export default function HomePage() {
  // All FAQ answers are plain strings now — maps directly to JSON-LD without patching
  const faqJsonLd = {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    mainEntity: faqsData.items.map((item) => ({
      "@type": "Question",
      name: item.q,
      acceptedAnswer: {
        "@type": "Answer",
        text: item.a as string,
      },
    })),
  };

  return (
    <>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqJsonLd) }} />
      <HomePageContent />
    </>
  );
}
