-- AlterTable
ALTER TABLE "User" ADD COLUMN "costBudgetEnabled" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "User" ADD COLUMN "monthlyBudget" DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "Game" ADD COLUMN "cost" DOUBLE PRECISION;
