name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - production
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha,prefix={{branch}}-

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64

      - name: Image digest
        run: echo ${{ steps.build-and-push.outputs.digest }}

  # Optional: Deploy to Cloud Run after build
  deploy-cloud-run:
    name: Deploy to Google Cloud Run
    needs: build-and-push
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    # Uncomment and configure if deploying to Cloud Run

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # - name: Authenticate to Google Cloud
      #   uses: google-github-actions/auth@v1
      #   with:
      #     credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      # - name: Set up Cloud SDK
      #   uses: google-github-actions/setup-gcloud@v1

      # - name: Deploy to Cloud Run
      #   run: |
      #     gcloud run deploy athletics-dashboard \
      #       --image ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:main \
      #       --platform managed \
      #       --region us-central1 \
      #       --memory 2Gi \
      #       --cpu 2 \
      #       --allow-unauthenticated

      - name: Placeholder
        run: echo "Configure Cloud Run deployment by uncommenting steps above"
