"use client";

import { Box, Typography, Link } from "@mui/material";
import BaseHeader from "@/components/headers/_base";

export default function DisclaimerPage() {
  return (
    <>
      <BaseHeader pt={"20px"} pl={"20px"} />
      <Box sx={{ maxWidth: 800, mx: "auto", p: 3 }}>
        <Typography variant="h4" gutterBottom>
          Disclaimer
        </Typography>

        <Typography variant="body1" paragraph>
          This Disclaimer applies to your use of Opletics (the "Platform"). By using the Platform, you acknowledge and agree to the terms below.
        </Typography>

        <Typography variant="h6" gutterBottom>
          1. Informational Use Only
        </Typography>
        <Typography variant="body1" paragraph>
          Opletics provides tools to help athletic departments manage schedules, communications, and operations. Content and outputs generated by the Platform (including any AI-assisted features) are for
          informational purposes only and should not be relied on as professional advice.
        </Typography>

        <Typography variant="h6" gutterBottom>
          2. No Guarantee of Accuracy
        </Typography>
        <Typography variant="body1" paragraph>
          Schedules, travel times, distances, costs, venue data, and other information may be incomplete, delayed, or inaccurate. You are responsible for verifying all information before relying on it,
          including confirming game times/locations and travel logistics with the appropriate parties.
        </Typography>

        <Typography variant="h6" gutterBottom>
          3. AI-Generated Recommendations
        </Typography>
        <Typography variant="body1" paragraph>
          If you use AI-powered features, you understand that AI outputs can be incorrect or misleading. You should independently review all AI-generated recommendations before acting on them.
        </Typography>

        <Typography variant="h6" gutterBottom>
          4. Third-Party Services
        </Typography>
        <Typography variant="body1" paragraph>
          The Platform may integrate with third-party services (such as Google Calendar, maps/distance services, email providers, and payment processors). We do not control these services and are not
          responsible for their availability, security, or content. Your use of third-party services is subject to their terms and privacy policies.
        </Typography>

        <Typography variant="h6" gutterBottom>
          5. School Policies and Legal Compliance
        </Typography>
        <Typography variant="body1" paragraph>
          You are responsible for ensuring your use of Opletics complies with applicable laws and school/district policies, including any student privacy requirements (such as FERPA). Nothing on the
          Platform is intended to provide legal advice.
        </Typography>

        <Typography variant="h6" gutterBottom>
          6. Limitation of Liability
        </Typography>
        <Typography variant="body1" paragraph>
          To the maximum extent permitted by law, Opletics is provided "as is" and we disclaim all warranties. We are not liable for any indirect, incidental, special, consequential, or punitive
          damages arising from your use of (or inability to use) the Platform.
        </Typography>

        <Typography variant="h6" gutterBottom>
          7. Contact
        </Typography>
        <Typography variant="body1" paragraph>
          Questions about this Disclaimer can be sent to <Link href="mailto:support@opletics.com">support@opletics.com</Link>.
        </Typography>

        <Typography variant="body2" color="text.secondary" sx={{ mt: 4 }}>
          Last updated: December 30, 2025
        </Typography>
      </Box>
    </>
  );
}
